/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseFileInput: typeof import('./src/components/BaseFileInput.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseSelectInput: typeof import('./src/components/BaseSelectInput.vue')['default']
    BaseTextarea: typeof import('./src/components/BaseTextarea.vue')['default']
    ContactUs: typeof import('./src/components/ContactUs.vue')['default']
    Cursor: typeof import('./src/components/Cursor.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    HowItWorks: typeof import('./src/components/HowItWorks.vue')['default']
    LoadingButton: typeof import('./src/components/LoadingButton.vue')['default']
    NavigationToggle: typeof import('./src/components/NavigationToggle.vue')['default']
    Prizes: typeof import('./src/components/Prizes.vue')['default']
    ScrollReminder: typeof import('./src/components/ScrollReminder.vue')['default']
    Sponsors: typeof import('./src/components/Sponsors.vue')['default']
    Submissions: typeof import('./src/components/Submissions.vue')['default']
    WhatTheySay: typeof import('./src/components/WhatTheySay.vue')['default']
    WhyIntellihack: typeof import('./src/components/WhyIntellihack.vue')['default']
  }
}
